/** Типы действий, фиксируемых в истории операций (аудит). */
export const HistoryAction = {
  TRIP_CREATED: 'TRIP_CREATED',
  TRIP_UPDATED: 'TRIP_UPDATED',
  MEMBER_ADDED: 'MEMBER_ADDED',
  MEMBER_UPDATED: 'MEMBER_UPDATED',
  MEMBER_DEACTIVATED: 'MEMBER_DEACTIVATED',
  EXPENSE_CREATED: 'EXPENSE_CREATED',
  EXPENSES_IMPORTED: 'EXPENSES_IMPORTED',
  EXPENSE_UPDATED: 'EXPENSE_UPDATED',
  EXPENSE_DELETED: 'EXPENSE_DELETED',
  FUND_CONTRIBUTED: 'FUND_CONTRIBUTED',
  FUND_PAID_OUT: 'FUND_PAID_OUT',
  FUND_ADJUSTED: 'FUND_ADJUSTED',
  SETTINGS_UPDATED: 'SETTINGS_UPDATED',
} as const;

export type HistoryActionType = (typeof HistoryAction)[keyof typeof HistoryAction];
